# 1.1 - Numpy  (Numerical Python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


NumPy es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal.

## Recordatorio de álgebra

+ Contenidos:

    + Concepto de tensor
    + Operaciones con vectores
        + Concepto de espacio vectorial y base
        + Suma de vectores
        + Producto escalar
        + Producto vectorial
    + Operaciones con matrices
        + Suma de matrices
        + Producto matricial
        + Matriz Identidad
        + Matriz Traspuesta (Hermítica)
        + Matriz Inversa 
        + Determinate

### Tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### Operaciones con vectores

**Espacio vectorial**

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.



**Base vectorial**

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}



**Suma de vectores**

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$



**Producto escalar**

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$



**Producto vectorial**

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### Operaciones con matrices


**Suma de matrices**

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$



**Producto matricial**

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
16 & 28 \\
4 & 14
\end{pmatrix}$$



**Matriz Identidad**

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$



**Matriz traspuesta  (hermítica)**

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


**Matriz Inversa**

¿Como se dividen las matrices? Se multiplica por la inversa. El cálculo de la matriz inversa es:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$


**Determinante**

$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$
  
  

**Veamos algo de todo esto en python:**


**Arrays**

In [2]:
import numpy as np   # as np es un alias, es para escribir menos

In [10]:
# nº aleatorio


np.random.random(1)

array([0.95946614])

In [11]:
type(np.random.random(1))

numpy.ndarray

In [12]:
np.random.random(1)[0]

0.5429219250892584

In [13]:
type(np.random.random(1)[0])

numpy.float64

In [14]:
vector = np.random.random(5)

vector

array([0.21703182, 0.93044429, 0.97565515, 0.52071011, 0.10191746])

In [15]:
type(vector)

numpy.ndarray

In [16]:
vector[2:5:2]

array([0.97565515, 0.10191746])

In [17]:
for e in vector:
    
    print(e)

0.2170318184672606
0.9304442893504956
0.9756551460839359
0.520710109778608
0.10191745513595785


In [18]:
2 * [1,2,3,4]

[1, 2, 3, 4, 1, 2, 3, 4]

In [19]:
2 * vector

array([0.43406364, 1.86088858, 1.95131029, 1.04142022, 0.20383491])

In [20]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [21]:
2 * np.array([1,2,3,4])

array([2, 4, 6, 8])

In [22]:
# matriz

matriz = np.random.random((10, 4))   # 10 filas y 4 columnas

matriz

array([[0.30220455, 0.72735969, 0.50854659, 0.13491667],
       [0.12634956, 0.37286095, 0.03827622, 0.39223509],
       [0.82717983, 0.80408309, 0.29738792, 0.05444636],
       [0.73209745, 0.02667171, 0.73524872, 0.17835819],
       [0.26035009, 0.10201228, 0.39776292, 0.01681878],
       [0.65623077, 0.76691432, 0.92430329, 0.57229916],
       [0.54634067, 0.67130854, 0.19376548, 0.83304111],
       [0.69670242, 0.65052695, 0.99688062, 0.39426996],
       [0.94942071, 0.01971841, 0.35309323, 0.20921797],
       [0.41873156, 0.44962539, 0.0046507 , 0.12909726]])

In [23]:
type(matriz)

numpy.ndarray

In [25]:
#help(matriz)

In [26]:
matriz[0]   # primera fila

array([0.30220455, 0.72735969, 0.50854659, 0.13491667])

In [27]:
matriz[0][0]

0.3022045502545131

In [28]:
matriz[0, 0]    # primera fila, primera columna

0.3022045502545131

In [29]:
matriz[1, 1] 

0.3728609484779287

In [30]:
matriz[:, 0]  # la primera columna (: todas las filas, 0 es la primera columna)

array([0.30220455, 0.12634956, 0.82717983, 0.73209745, 0.26035009,
       0.65623077, 0.54634067, 0.69670242, 0.94942071, 0.41873156])

In [31]:
matriz[0, :]    # la primera fila

array([0.30220455, 0.72735969, 0.50854659, 0.13491667])

In [32]:
matriz[0]

array([0.30220455, 0.72735969, 0.50854659, 0.13491667])

**slicing**

los `:` signican todo, es decir, todas las filas. Luego, separado por coma, el 0, primer elemento de cada fila, es decir, la primera columna

In [33]:
# cubo 

cubo = np.random.random((3, 3, 2))  # 3 capas, 3 filas, 2 columnas

cubo

array([[[0.04552583, 0.95018471],
        [0.2427826 , 0.31791529],
        [0.70513839, 0.8267854 ]],

       [[0.50281993, 0.85638899],
        [0.36667766, 0.89248385],
        [0.80355866, 0.43337917]],

       [[0.34608296, 0.86033765],
        [0.52695578, 0.15964206],
        [0.17220316, 0.07622434]]])

In [34]:
# tensor rango 4

tensor = np.random.random((2, 3, 4, 5))   # 2 cubos, 3 capas, 4 filas, 5 columnas

tensor


array([[[[0.67189297, 0.87425925, 0.96736258, 0.93368205, 0.49888914],
         [0.93864652, 0.3825013 , 0.6682448 , 0.86868671, 0.43481483],
         [0.82738413, 0.73329536, 0.09883287, 0.829611  , 0.13133703],
         [0.58927858, 0.81916551, 0.23905352, 0.35312467, 0.9909967 ]],

        [[0.2101275 , 0.32558568, 0.83568986, 0.29058954, 0.29407828],
         [0.64477928, 0.29493319, 0.08546955, 0.61869589, 0.46628762],
         [0.5687018 , 0.81468488, 0.07582589, 0.58714329, 0.927846  ],
         [0.39048598, 0.81149888, 0.64089811, 0.68356072, 0.74375933]],

        [[0.28275735, 0.72019016, 0.14668611, 0.79114636, 0.5290326 ],
         [0.30131542, 0.13127239, 0.45220748, 0.56476493, 0.75088255],
         [0.9968856 , 0.41006507, 0.50083528, 0.03708159, 0.17492507],
         [0.95572963, 0.21712272, 0.62185204, 0.28079114, 0.42931312]]],


       [[[0.87513774, 0.86913958, 0.4629265 , 0.71474415, 0.3021769 ],
         [0.52827879, 0.11350598, 0.77092796, 0.68059167, 0.38291312]

In [35]:
matriz.shape

(10, 4)

In [36]:
cubo.shape

(3, 3, 2)

In [37]:
matriz.size

40

In [38]:
cubo.size

18

In [39]:
tensor[0][0][0][0]

0.6718929717437201

In [40]:
tensor[0, 0, 0, 0]

0.6718929717437201

In [41]:
tensor[0, 0, 0, -1]

0.49888914226790215

In [43]:
tensor[4]

IndexError: index 4 is out of bounds for axis 0 with size 2

In [44]:
lst = [1,2,3]


lst[4]

IndexError: list index out of range

**Operaciones matemáticas**

In [45]:
matriz

array([[0.30220455, 0.72735969, 0.50854659, 0.13491667],
       [0.12634956, 0.37286095, 0.03827622, 0.39223509],
       [0.82717983, 0.80408309, 0.29738792, 0.05444636],
       [0.73209745, 0.02667171, 0.73524872, 0.17835819],
       [0.26035009, 0.10201228, 0.39776292, 0.01681878],
       [0.65623077, 0.76691432, 0.92430329, 0.57229916],
       [0.54634067, 0.67130854, 0.19376548, 0.83304111],
       [0.69670242, 0.65052695, 0.99688062, 0.39426996],
       [0.94942071, 0.01971841, 0.35309323, 0.20921797],
       [0.41873156, 0.44962539, 0.0046507 , 0.12909726]])

In [46]:
matriz.sum()

17.471305188388456

In [47]:
sum(matriz)

array([5.51560761, 4.59108134, 4.4499157 , 2.91470054])

In [48]:
matriz.sum(axis=0) # suma por columnas

array([5.51560761, 4.59108134, 4.4499157 , 2.91470054])

In [49]:
matriz.sum(axis=1) # suma por filas

array([1.6730275 , 0.92972182, 1.98309721, 1.67237607, 0.77694407,
       2.91974755, 2.2444558 , 2.73837995, 1.53145031, 1.00210492])

In [50]:
matriz.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [51]:
cubo.sum(axis=2)

array([[0.99571054, 0.56069789, 1.53192379],
       [1.35920892, 1.25916151, 1.23693783],
       [1.20642061, 0.68659784, 0.2484275 ]])

In [53]:
matriz[:, 2].sum()

4.449915697092947

In [54]:
matriz.min()

0.004650703730827321

In [55]:
matriz.max()

0.996880616855162

In [56]:
matriz.max(axis=0)

array([0.94942071, 0.80408309, 0.99688062, 0.83304111])

In [57]:
matriz.max(axis=1)

array([0.72735969, 0.39223509, 0.82717983, 0.73524872, 0.39776292,
       0.92430329, 0.83304111, 0.99688062, 0.94942071, 0.44962539])

In [58]:
cubo.shape

(3, 3, 2)

In [59]:
cubo.sum(axis=0).shape   # por capas

(3, 2)

In [60]:
cubo.sum(axis=1).shape   # por filas

(3, 2)

In [61]:
cubo.sum(axis=2).shape   # por columnas

(3, 3)

In [63]:
matriz[0:2, 0:2]  # Aij : matriz[filas, columnas]

array([[0.30220455, 0.72735969],
       [0.12634956, 0.37286095]])

In [64]:
matriz[0:2, 0:2].max()

0.7273596921892761

In [65]:
# calculo del max


lst = [54,6, 445646456, 7,8,8,6,5,4,3,5,6,6,6,6,6,7,7777]



def maximo(lst):
    
    el_maximo = 0
    
    for e in lst:
        
        if e > el_maximo:
            
            el_maximo = e
            
    return el_maximo

In [66]:
%%time

maximo(lst)

CPU times: user 10 µs, sys: 13 µs, total: 23 µs
Wall time: 35.8 µs


445646456

In [67]:
%%time

max(lst)

CPU times: user 4 µs, sys: 1e+03 ns, total: 5 µs
Wall time: 8.11 µs


445646456

In [68]:
lst_array = np.array(lst)

In [69]:
%%time

lst_array.max()

CPU times: user 65 µs, sys: 240 µs, total: 305 µs
Wall time: 313 µs


445646456

In [74]:
%%time

lst = [i for i in range(10_000_000)]

[e+2 for e in lst][:10]

CPU times: user 450 ms, sys: 185 ms, total: 635 ms
Wall time: 752 ms


[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [75]:
%%time

a = np.array(lst) + 2   # vectorizado

a[:10]

CPU times: user 307 ms, sys: 9.94 ms, total: 317 ms
Wall time: 315 ms


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
list(np.array([1,2,34,4]))

[1, 2, 34, 4]

In [79]:
matriz.mean()

0.4367826297097114

In [80]:
matriz.mean(axis=0)

array([0.55156076, 0.45910813, 0.44499157, 0.29147005])

In [82]:
matriz.std()

0.2978177432807798

In [83]:
matriz.var()

0.08869540821285646

In [84]:
matriz.var() ** 0.5

0.2978177432807798

In [85]:
matriz.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [86]:
np.median(matriz)

0.39601643956974525

In [87]:
np.add(matriz[0], matriz[1])   # suma de vectores

array([0.42855411, 1.10022064, 0.54682281, 0.52715176])

In [88]:
np.subtract(matriz[0], matriz[1])   # resta de vectores

array([ 0.17585499,  0.35449874,  0.47027036, -0.25731842])

In [89]:
np.multiply(matriz[0], matriz[1])   # multiplica elemento a elemento

array([0.03818341, 0.27120402, 0.01946524, 0.05291905])

In [90]:
np.dot(matriz[0], matriz[1])   # multiplicacion escalar

0.3817717322462421

In [92]:
np.dot(matriz.T, matriz)

array([[3.68652414, 2.50838178, 2.79047468, 1.62838879],
       [2.50838178, 2.99029478, 2.17996872, 1.61142045],
       [2.79047468, 2.17996872, 3.05767936, 1.39555043],
       [1.62838879, 1.61142045, 1.39555043, 1.44448068]])

In [93]:
matriz

array([[0.30220455, 0.72735969, 0.50854659, 0.13491667],
       [0.12634956, 0.37286095, 0.03827622, 0.39223509],
       [0.82717983, 0.80408309, 0.29738792, 0.05444636],
       [0.73209745, 0.02667171, 0.73524872, 0.17835819],
       [0.26035009, 0.10201228, 0.39776292, 0.01681878],
       [0.65623077, 0.76691432, 0.92430329, 0.57229916],
       [0.54634067, 0.67130854, 0.19376548, 0.83304111],
       [0.69670242, 0.65052695, 0.99688062, 0.39426996],
       [0.94942071, 0.01971841, 0.35309323, 0.20921797],
       [0.41873156, 0.44962539, 0.0046507 , 0.12909726]])

In [94]:
matriz.T

array([[0.30220455, 0.12634956, 0.82717983, 0.73209745, 0.26035009,
        0.65623077, 0.54634067, 0.69670242, 0.94942071, 0.41873156],
       [0.72735969, 0.37286095, 0.80408309, 0.02667171, 0.10201228,
        0.76691432, 0.67130854, 0.65052695, 0.01971841, 0.44962539],
       [0.50854659, 0.03827622, 0.29738792, 0.73524872, 0.39776292,
        0.92430329, 0.19376548, 0.99688062, 0.35309323, 0.0046507 ],
       [0.13491667, 0.39223509, 0.05444636, 0.17835819, 0.01681878,
        0.57229916, 0.83304111, 0.39426996, 0.20921797, 0.12909726]])

In [95]:
np.dot(matriz, matriz)

ValueError: shapes (10,4) and (10,4) not aligned: 4 (dim 1) != 10 (dim 0)

In [96]:
%%time

np.dot(matriz.T, matriz)   # producto de matrices

CPU times: user 139 µs, sys: 62 µs, total: 201 µs
Wall time: 204 µs


array([[3.68652414, 2.50838178, 2.79047468, 1.62838879],
       [2.50838178, 2.99029478, 2.17996872, 1.61142045],
       [2.79047468, 2.17996872, 3.05767936, 1.39555043],
       [1.62838879, 1.61142045, 1.39555043, 1.44448068]])

In [98]:
%%time

np.matmul(matriz.T, matriz)   # producto de matrices

CPU times: user 63 µs, sys: 35 µs, total: 98 µs
Wall time: 107 µs


array([[3.68652414, 2.50838178, 2.79047468, 1.62838879],
       [2.50838178, 2.99029478, 2.17996872, 1.61142045],
       [2.79047468, 2.17996872, 3.05767936, 1.39555043],
       [1.62838879, 1.61142045, 1.39555043, 1.44448068]])

In [99]:
matriz.T.shape

(4, 10)

In [100]:
matriz.shape

(10, 4)

In [102]:
matriz.transpose().shape

(4, 10)

In [103]:
matriz[0] + matriz[1]

array([0.42855411, 1.10022064, 0.54682281, 0.52715176])

In [104]:
matriz[0] - matriz[1]

array([ 0.17585499,  0.35449874,  0.47027036, -0.25731842])

In [105]:
np.cross(matriz[0],  matriz[1])   # producto vectorial

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [106]:
np.cross(matriz[0][:3],  matriz[1][:3])

array([-0.16177658,  0.05268739,  0.0207787 ])

In [107]:
matriz[0][:3]

array([0.30220455, 0.72735969, 0.50854659])

In [108]:
np.tensordot(matriz, matriz)

array(11.17897895)

In [109]:
matriz

array([[0.30220455, 0.72735969, 0.50854659, 0.13491667],
       [0.12634956, 0.37286095, 0.03827622, 0.39223509],
       [0.82717983, 0.80408309, 0.29738792, 0.05444636],
       [0.73209745, 0.02667171, 0.73524872, 0.17835819],
       [0.26035009, 0.10201228, 0.39776292, 0.01681878],
       [0.65623077, 0.76691432, 0.92430329, 0.57229916],
       [0.54634067, 0.67130854, 0.19376548, 0.83304111],
       [0.69670242, 0.65052695, 0.99688062, 0.39426996],
       [0.94942071, 0.01971841, 0.35309323, 0.20921797],
       [0.41873156, 0.44962539, 0.0046507 , 0.12909726]])

In [110]:
matriz.cumsum()    # suma acumulada

array([ 0.30220455,  1.02956424,  1.53811083,  1.6730275 ,  1.79937706,
        2.17223801,  2.21051423,  2.60274932,  3.42992916,  4.23401225,
        4.53140017,  4.58584653,  5.31794398,  5.34461569,  6.07986441,
        6.2582226 ,  6.51857268,  6.62058496,  7.01834789,  7.03516667,
        7.69139743,  8.45831176,  9.38261505,  9.95491421, 10.50125488,
       11.17256342, 11.3663289 , 12.19937001, 12.89607243, 13.54659939,
       14.54348   , 14.93774996, 15.88717067, 15.90688908, 16.2599823 ,
       16.46920027, 16.88793183, 17.33755723, 17.34220793, 17.47130519])

In [111]:
matriz.sum()

17.471305188388456

In [112]:
matriz.cumprod()    # producto acumulado

array([3.02204550e-01, 2.19811409e-01, 1.11784342e-01, 1.50815713e-02,
       1.90554986e-03, 7.10505128e-04, 2.71954535e-05, 1.06670112e-05,
       8.82353657e-06, 7.09485657e-06, 2.10992466e-06, 1.14877714e-07,
       8.41016819e-08, 2.24313537e-09, 1.64926241e-09, 2.94159458e-10,
       7.65844406e-11, 7.81255330e-12, 3.10754404e-12, 5.22650955e-14,
       3.42979638e-14, 2.63035997e-14, 2.43125039e-14, 1.39140256e-14,
       7.60179799e-15, 5.10315191e-15, 9.88814681e-16, 8.23723280e-16,
       5.73890006e-16, 3.73330917e-16, 3.72166355e-16, 1.46734012e-16,
       1.39312310e-16, 2.74701708e-18, 9.69953123e-19, 2.02931620e-19,
       8.49738739e-20, 3.82064116e-20, 1.77686701e-22, 2.29388659e-23])

In [113]:
1e2   # notacion cientifica

100.0

In [114]:
1e-2

0.01

In [115]:
np.inf

inf

In [116]:
type(np.inf)

float

In [117]:
1/np.inf

0.0

In [118]:
np.nan    # nan = Not a number

nan

In [119]:
None

In [120]:
type(np.nan)

float

In [121]:
type(None)

NoneType

In [122]:
np.pi

3.141592653589793

In [123]:
np.exp

<ufunc 'exp'>

In [124]:
np.exp(8)

2980.9579870417283

In [125]:
np.log

<ufunc 'log'>

In [126]:
np.cos

<ufunc 'cos'>

In [127]:
np.sin

<ufunc 'sin'>

In [128]:
np.tan

<ufunc 'tan'>

**Dimensiones**

In [129]:
matriz.shape

(10, 4)

In [130]:
matriz

array([[0.30220455, 0.72735969, 0.50854659, 0.13491667],
       [0.12634956, 0.37286095, 0.03827622, 0.39223509],
       [0.82717983, 0.80408309, 0.29738792, 0.05444636],
       [0.73209745, 0.02667171, 0.73524872, 0.17835819],
       [0.26035009, 0.10201228, 0.39776292, 0.01681878],
       [0.65623077, 0.76691432, 0.92430329, 0.57229916],
       [0.54634067, 0.67130854, 0.19376548, 0.83304111],
       [0.69670242, 0.65052695, 0.99688062, 0.39426996],
       [0.94942071, 0.01971841, 0.35309323, 0.20921797],
       [0.41873156, 0.44962539, 0.0046507 , 0.12909726]])

In [131]:
matriz.size

40

In [132]:
matriz.reshape((5, 8))

array([[0.30220455, 0.72735969, 0.50854659, 0.13491667, 0.12634956,
        0.37286095, 0.03827622, 0.39223509],
       [0.82717983, 0.80408309, 0.29738792, 0.05444636, 0.73209745,
        0.02667171, 0.73524872, 0.17835819],
       [0.26035009, 0.10201228, 0.39776292, 0.01681878, 0.65623077,
        0.76691432, 0.92430329, 0.57229916],
       [0.54634067, 0.67130854, 0.19376548, 0.83304111, 0.69670242,
        0.65052695, 0.99688062, 0.39426996],
       [0.94942071, 0.01971841, 0.35309323, 0.20921797, 0.41873156,
        0.44962539, 0.0046507 , 0.12909726]])

In [133]:
matriz.reshape((8, 5))

array([[0.30220455, 0.72735969, 0.50854659, 0.13491667, 0.12634956],
       [0.37286095, 0.03827622, 0.39223509, 0.82717983, 0.80408309],
       [0.29738792, 0.05444636, 0.73209745, 0.02667171, 0.73524872],
       [0.17835819, 0.26035009, 0.10201228, 0.39776292, 0.01681878],
       [0.65623077, 0.76691432, 0.92430329, 0.57229916, 0.54634067],
       [0.67130854, 0.19376548, 0.83304111, 0.69670242, 0.65052695],
       [0.99688062, 0.39426996, 0.94942071, 0.01971841, 0.35309323],
       [0.20921797, 0.41873156, 0.44962539, 0.0046507 , 0.12909726]])

In [134]:
matriz.reshape((8, 8))

ValueError: cannot reshape array of size 40 into shape (8,8)

In [135]:
matriz.reshape((5, 4, 2))

array([[[0.30220455, 0.72735969],
        [0.50854659, 0.13491667],
        [0.12634956, 0.37286095],
        [0.03827622, 0.39223509]],

       [[0.82717983, 0.80408309],
        [0.29738792, 0.05444636],
        [0.73209745, 0.02667171],
        [0.73524872, 0.17835819]],

       [[0.26035009, 0.10201228],
        [0.39776292, 0.01681878],
        [0.65623077, 0.76691432],
        [0.92430329, 0.57229916]],

       [[0.54634067, 0.67130854],
        [0.19376548, 0.83304111],
        [0.69670242, 0.65052695],
        [0.99688062, 0.39426996]],

       [[0.94942071, 0.01971841],
        [0.35309323, 0.20921797],
        [0.41873156, 0.44962539],
        [0.0046507 , 0.12909726]]])

In [136]:
matriz.flatten()

array([0.30220455, 0.72735969, 0.50854659, 0.13491667, 0.12634956,
       0.37286095, 0.03827622, 0.39223509, 0.82717983, 0.80408309,
       0.29738792, 0.05444636, 0.73209745, 0.02667171, 0.73524872,
       0.17835819, 0.26035009, 0.10201228, 0.39776292, 0.01681878,
       0.65623077, 0.76691432, 0.92430329, 0.57229916, 0.54634067,
       0.67130854, 0.19376548, 0.83304111, 0.69670242, 0.65052695,
       0.99688062, 0.39426996, 0.94942071, 0.01971841, 0.35309323,
       0.20921797, 0.41873156, 0.44962539, 0.0046507 , 0.12909726])

In [138]:
matriz.flatten().shape

(40,)

In [139]:
cubo.flatten().shape

(18,)

In [140]:
tensor.flatten().shape

(120,)

In [146]:
np.stack((matriz, matriz, matriz)).shape

(3, 10, 4)

In [148]:
# matriz identidad

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [149]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [150]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [151]:
a = np.array([[1, 2], 
              [3, 4]])

np.linalg.det(a)

-2.0000000000000004

In [152]:
a

array([[1, 2],
       [3, 4]])

In [153]:
# condicional

np.where

<function numpy.where>

In [155]:
# np.where(condicion, if, else)

np.where(matriz > 0.5, 1, 0) # con la condicion me das un 1, else 0

array([[0, 1, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0]])

In [156]:
np.where(matriz > 0.5, 1, np.where(matriz < 0.5, 2, 0)) # esto sera 0 si elem == 0.5

array([[2, 1, 1, 2],
       [2, 2, 2, 2],
       [1, 1, 2, 2],
       [1, 2, 1, 2],
       [2, 2, 2, 2],
       [1, 1, 1, 1],
       [1, 1, 2, 1],
       [1, 1, 1, 2],
       [1, 2, 2, 2],
       [2, 2, 2, 2]])

In [157]:
np.where(matriz > 0.5, 'hola', np.where(matriz < 0.5, 'adios', 0))

array([['adios', 'hola', 'hola', 'adios'],
       ['adios', 'adios', 'adios', 'adios'],
       ['hola', 'hola', 'adios', 'adios'],
       ['hola', 'adios', 'hola', 'adios'],
       ['adios', 'adios', 'adios', 'adios'],
       ['hola', 'hola', 'hola', 'hola'],
       ['hola', 'hola', 'adios', 'hola'],
       ['hola', 'hola', 'hola', 'adios'],
       ['hola', 'adios', 'adios', 'adios'],
       ['adios', 'adios', 'adios', 'adios']], dtype='<U21')

In [160]:
np.version

<module 'numpy.version' from '/opt/homebrew/Caskroom/miniconda/base/envs/clase/lib/python3.9/site-packages/numpy/version.py'>

In [163]:
np.empty(0)

array([], dtype=float64)