# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.1'

In [3]:
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/opt/arm64-builds/lib']
    lang

In [4]:
np.empty((2, 3, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [5]:
a = np.random.random((2, 3, 5))

In [6]:
a

array([[[0.50941193, 0.68819739, 0.87729553, 0.61785377, 0.57347641],
        [0.01301543, 0.98587231, 0.24467503, 0.10420571, 0.83397552],
        [0.91609149, 0.5337963 , 0.79055486, 0.88567299, 0.34188902]],

       [[0.89696033, 0.19393062, 0.85578119, 0.31989216, 0.24396504],
        [0.42303238, 0.49446719, 0.44055659, 0.73796809, 0.53175819],
        [0.26725587, 0.93149933, 0.58977581, 0.93209337, 0.62832117]]])

In [7]:
np.random.rand(2, 3, 5)

array([[[0.20613007, 0.32432211, 0.26772088, 0.10700058, 0.33828726],
        [0.84732803, 0.9285873 , 0.9927981 , 0.64130861, 0.81439517],
        [0.41275426, 0.25501606, 0.66519113, 0.65790925, 0.69794537]],

       [[0.58237088, 0.3057491 , 0.44398225, 0.06565279, 0.6143629 ],
        [0.5833966 , 0.39970574, 0.4805861 , 0.59107301, 0.38895117],
        [0.3876661 , 0.82572903, 0.10404504, 0.30751048, 0.97464994]]])

In [8]:
np.random.random_sample((2, 3, 5))

array([[[0.57691817, 0.30784863, 0.88870597, 0.44554978, 0.56792489],
        [0.27818925, 0.64222958, 0.80232097, 0.72387298, 0.24719434],
        [0.85575509, 0.70999834, 0.36134394, 0.24265127, 0.46202228]],

       [[0.39832434, 0.43809669, 0.15217486, 0.97844644, 0.49004474],
        [0.9091031 , 0.72640813, 0.72560717, 0.84637714, 0.13216423],
        [0.71723485, 0.20810604, 0.9946872 , 0.67943526, 0.26265338]]])

In [9]:
np.random.randint(2, 3, 5)

array([2, 2, 2, 2, 2])

In [10]:
a

array([[[0.50941193, 0.68819739, 0.87729553, 0.61785377, 0.57347641],
        [0.01301543, 0.98587231, 0.24467503, 0.10420571, 0.83397552],
        [0.91609149, 0.5337963 , 0.79055486, 0.88567299, 0.34188902]],

       [[0.89696033, 0.19393062, 0.85578119, 0.31989216, 0.24396504],
        [0.42303238, 0.49446719, 0.44055659, 0.73796809, 0.53175819],
        [0.26725587, 0.93149933, 0.58977581, 0.93209337, 0.62832117]]])

In [11]:
dim = [5, 2, 3]  # 5 capas, 2 filas, 3 columnas

b = np.ones(dim)

b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
a.size == b.size

True

In [13]:
a.size

30

In [14]:
b.size

30

In [15]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [16]:
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [17]:
b.T.shape

(3, 2, 5)

In [18]:
b.transpose(0, 1, 2).shape

(5, 2, 3)

In [19]:
b.transpose(1, 2, 0).shape

(2, 3, 5)

In [20]:
a + b.transpose(1, 2, 0)

array([[[1.50941193, 1.68819739, 1.87729553, 1.61785377, 1.57347641],
        [1.01301543, 1.98587231, 1.24467503, 1.10420571, 1.83397552],
        [1.91609149, 1.5337963 , 1.79055486, 1.88567299, 1.34188902]],

       [[1.89696033, 1.19393062, 1.85578119, 1.31989216, 1.24396504],
        [1.42303238, 1.49446719, 1.44055659, 1.73796809, 1.53175819],
        [1.26725587, 1.93149933, 1.58977581, 1.93209337, 1.62832117]]])

In [21]:
np.add(a, b.transpose(1, 2, 0))

array([[[1.50941193, 1.68819739, 1.87729553, 1.61785377, 1.57347641],
        [1.01301543, 1.98587231, 1.24467503, 1.10420571, 1.83397552],
        [1.91609149, 1.5337963 , 1.79055486, 1.88567299, 1.34188902]],

       [[1.89696033, 1.19393062, 1.85578119, 1.31989216, 1.24396504],
        [1.42303238, 1.49446719, 1.44055659, 1.73796809, 1.53175819],
        [1.26725587, 1.93149933, 1.58977581, 1.93209337, 1.62832117]]])

In [22]:
c = b.transpose(1, 2, 0)

In [23]:
d = np.add(a, c)

d

array([[[1.50941193, 1.68819739, 1.87729553, 1.61785377, 1.57347641],
        [1.01301543, 1.98587231, 1.24467503, 1.10420571, 1.83397552],
        [1.91609149, 1.5337963 , 1.79055486, 1.88567299, 1.34188902]],

       [[1.89696033, 1.19393062, 1.85578119, 1.31989216, 1.24396504],
        [1.42303238, 1.49446719, 1.44055659, 1.73796809, 1.53175819],
        [1.26725587, 1.93149933, 1.58977581, 1.93209337, 1.62832117]]])

In [24]:
np.multiply(a, c)

array([[[0.50941193, 0.68819739, 0.87729553, 0.61785377, 0.57347641],
        [0.01301543, 0.98587231, 0.24467503, 0.10420571, 0.83397552],
        [0.91609149, 0.5337963 , 0.79055486, 0.88567299, 0.34188902]],

       [[0.89696033, 0.19393062, 0.85578119, 0.31989216, 0.24396504],
        [0.42303238, 0.49446719, 0.44055659, 0.73796809, 0.53175819],
        [0.26725587, 0.93149933, 0.58977581, 0.93209337, 0.62832117]]])

In [25]:
a * c

array([[[0.50941193, 0.68819739, 0.87729553, 0.61785377, 0.57347641],
        [0.01301543, 0.98587231, 0.24467503, 0.10420571, 0.83397552],
        [0.91609149, 0.5337963 , 0.79055486, 0.88567299, 0.34188902]],

       [[0.89696033, 0.19393062, 0.85578119, 0.31989216, 0.24396504],
        [0.42303238, 0.49446719, 0.44055659, 0.73796809, 0.53175819],
        [0.26725587, 0.93149933, 0.58977581, 0.93209337, 0.62832117]]])

In [26]:
e = a * c

e

array([[[0.50941193, 0.68819739, 0.87729553, 0.61785377, 0.57347641],
        [0.01301543, 0.98587231, 0.24467503, 0.10420571, 0.83397552],
        [0.91609149, 0.5337963 , 0.79055486, 0.88567299, 0.34188902]],

       [[0.89696033, 0.19393062, 0.85578119, 0.31989216, 0.24396504],
        [0.42303238, 0.49446719, 0.44055659, 0.73796809, 0.53175819],
        [0.26725587, 0.93149933, 0.58977581, 0.93209337, 0.62832117]]])

In [27]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [28]:
a is e

False

In [29]:
id(a)

4428175280

In [30]:
id(e)

4428485808

In [31]:
d_max = d.max()

d_max

1.9858723131796956

In [32]:
d_mean = d.mean()

d_mean

1.580108034403412

In [33]:
d_min = d.min()

d_min

1.0130154316677804

In [34]:
f = np.empty((2, 3, 5))   # esto esta vacio

f

array([[[0.50941193, 0.68819739, 0.87729553, 0.61785377, 0.57347641],
        [0.01301543, 0.98587231, 0.24467503, 0.10420571, 0.83397552],
        [0.91609149, 0.5337963 , 0.79055486, 0.88567299, 0.34188902]],

       [[0.89696033, 0.19393062, 0.85578119, 0.31989216, 0.24396504],
        [0.42303238, 0.49446719, 0.44055659, 0.73796809, 0.53175819],
        [0.26725587, 0.93149933, 0.58977581, 0.93209337, 0.62832117]]])

In [35]:
d

array([[[1.50941193, 1.68819739, 1.87729553, 1.61785377, 1.57347641],
        [1.01301543, 1.98587231, 1.24467503, 1.10420571, 1.83397552],
        [1.91609149, 1.5337963 , 1.79055486, 1.88567299, 1.34188902]],

       [[1.89696033, 1.19393062, 1.85578119, 1.31989216, 1.24396504],
        [1.42303238, 1.49446719, 1.44055659, 1.73796809, 1.53175819],
        [1.26725587, 1.93149933, 1.58977581, 1.93209337, 1.62832117]]])

In [36]:
f.shape

(2, 3, 5)

In [37]:
for capa in range(f.shape[0]):   # 2 capas
    
    for fila in range(f.shape[1]):   # 3 filas
        
        for col in range(f.shape[2]):  # 5 columnas
            
            
            if d_min == d[capa][fila][col]: # si es el minimo ponme cero en f
                
                f[capa][fila][col] = 0
                
            
            elif d_min < d[capa][fila][col] < d_mean: # si esta entre el minimo y la media ponme 25
                
                f[capa][fila][col] = 25
                
                
            elif d_mean == d[capa][fila][col]: # si es la media ponme 50 en f
                
                f[capa][fila][col] = 50
                
                
            elif d_mean < d[capa][fila][col] < d_max: # si esta entre la media y el maximo ponme 75
                
                f[capa][fila][col] = 75
                
                
            elif d_max == d[capa][fila][col]: # si es el maximo ponme 100 en f
                
                f[capa][fila][col] = 100
        
        
        

    
    

In [38]:
f

array([[[ 25.,  75.,  75.,  75.,  25.],
        [  0., 100.,  25.,  25.,  75.],
        [ 75.,  25.,  75.,  75.,  25.]],

       [[ 75.,  25.,  75.,  25.,  25.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  75.,  75.]]])

In [40]:


f = f.astype('str')   # a formato string


for capa in range(f.shape[0]):   # 2 capas
    
    for fila in range(f.shape[1]):   # 3 filas
        
        for col in range(f.shape[2]):  # 5 columnas
            
            
            if d_min == d[capa][fila][col]: # si es el minimo ponme A en f
                
                f[capa][fila][col] = 'A'
                
            
            elif d_min < d[capa][fila][col] < d_mean: # si esta entre el minimo y la media ponme B
                
                f[capa][fila][col] = 'B'
                
                
            elif d_mean == d[capa][fila][col]: # si es la media ponme C en f
                
                f[capa][fila][col] = 'C'
                
                
            elif d_mean < d[capa][fila][col] < d_max: # si esta entre la media y el maximo ponme D
                
                f[capa][fila][col] = 'D'
                
                
            elif d_max == d[capa][fila][col]: # si es el maximo ponme E en f
                
                f[capa][fila][col] = 'E'
        
        
        

    
    

In [41]:
f

array([[['B', 'D', 'D', 'D', 'B'],
        ['A', 'E', 'B', 'B', 'D'],
        ['D', 'B', 'D', 'D', 'B']],

       [['D', 'B', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'D', 'B'],
        ['B', 'D', 'D', 'D', 'D']]], dtype='<U32')

In [43]:
type(str(f))

str

In [44]:
type(f)

numpy.ndarray

In [45]:
np.array(str(f))

array("[[['B' 'D' 'D' 'D' 'B']\n  ['A' 'E' 'B' 'B' 'D']\n  ['D' 'B' 'D' 'D' 'B']]\n\n [['D' 'B' 'D' 'B' 'B']\n  ['B' 'B' 'B' 'D' 'B']\n  ['B' 'D' 'D' 'D' 'D']]]",
      dtype='<U147')

In [46]:
np.array(str(f)).shape

()

In [50]:
np.array(str(f)).size

1

In [48]:
np.array(str(f))

array("[[['B' 'D' 'D' 'D' 'B']\n  ['A' 'E' 'B' 'B' 'D']\n  ['D' 'B' 'D' 'D' 'B']]\n\n [['D' 'B' 'D' 'B' 'B']\n  ['B' 'B' 'B' 'D' 'B']\n  ['B' 'D' 'D' 'D' 'D']]]",
      dtype='<U147')

In [49]:
str(f)

"[[['B' 'D' 'D' 'D' 'B']\n  ['A' 'E' 'B' 'B' 'D']\n  ['D' 'B' 'D' 'D' 'B']]\n\n [['D' 'B' 'D' 'B' 'B']\n  ['B' 'B' 'B' 'D' 'B']\n  ['B' 'D' 'D' 'D' 'D']]]"

In [52]:
[1,2,3,4][0]

1

In [54]:
str([1,2,3,4])[0]

'['

# Import Export

In [55]:
import pandas as pd

In [56]:
ruta = 'datasets/nasa.json'

In [58]:
json_data = pd.read_json(ruta)

json_data.head()

:@computed_region_cbhk_fwbd  :@computed_region_nnqa_25f4  fall  \
0                          NaN                          NaN  Fell   
1                          NaN                          NaN  Fell   
2                          NaN                          NaN  Fell   
3                          NaN                          NaN  Fell   
4                          NaN                          NaN  Fell   

                                         geolocation   id      mass      name  \
0  {'type': 'Point', 'coordinates': [6.08333, 50....    1      21.0    Aachen   
1  {'type': 'Point', 'coordinates': [10.23333, 56...    2     720.0    Aarhus   
2  {'type': 'Point', 'coordinates': [-113, 54.216...    6  107000.0      Abee   
3  {'type': 'Point', 'coordinates': [-99.9, 16.88...   10    1914.0  Acapulco   
4  {'type': 'Point', 'coordinates': [-64.95, -33....  370     780.0   Achiras   

  nametype     recclass    reclat    reclong                     year  
0    Valid           L5  50.77500    6.08333  1880-01-01T00:00:00.000  
1    Valid           H6  56.18333   10.23333  1951-01-01T00:00:00.000  
2    Valid          EH4  54.21667 -113.00000  1952-01-01T00:00:00.000  
3    Valid  Acapulcoite  16.88333  -99.90000  1976-01-01T00:00:00.000  
4    Valid           L6 -33.16667  -64.95000  1902-01-01T00:00:00.000

In [59]:
nasa = pd.read_json(ruta)

nasa.head()

:@computed_region_cbhk_fwbd  :@computed_region_nnqa_25f4  fall  \
0                          NaN                          NaN  Fell   
1                          NaN                          NaN  Fell   
2                          NaN                          NaN  Fell   
3                          NaN                          NaN  Fell   
4                          NaN                          NaN  Fell   

                                         geolocation   id      mass      name  \
0  {'type': 'Point', 'coordinates': [6.08333, 50....    1      21.0    Aachen   
1  {'type': 'Point', 'coordinates': [10.23333, 56...    2     720.0    Aarhus   
2  {'type': 'Point', 'coordinates': [-113, 54.216...    6  107000.0      Abee   
3  {'type': 'Point', 'coordinates': [-99.9, 16.88...   10    1914.0  Acapulco   
4  {'type': 'Point', 'coordinates': [-64.95, -33....  370     780.0   Achiras   

  nametype     recclass    reclat    reclong                     year  
0    Valid           L5  50.77500    6.08333  1880-01-01T00:00:00.000  
1    Valid           H6  56.18333   10.23333  1951-01-01T00:00:00.000  
2    Valid          EH4  54.21667 -113.00000  1952-01-01T00:00:00.000  
3    Valid  Acapulcoite  16.88333  -99.90000  1976-01-01T00:00:00.000  
4    Valid           L6 -33.16667  -64.95000  1902-01-01T00:00:00.000

In [60]:
print(nasa)

     :@computed_region_cbhk_fwbd  :@computed_region_nnqa_25f4  fall  \
0                            NaN                          NaN  Fell   
1                            NaN                          NaN  Fell   
2                            NaN                          NaN  Fell   
3                            NaN                          NaN  Fell   
4                            NaN                          NaN  Fell   
..                           ...                          ...   ...   
995                          NaN                          NaN  Fell   
996                          NaN                          NaN  Fell   
997                          NaN                          NaN  Fell   
998                          NaN                          NaN  Fell   
999                          NaN                          NaN  Fell   

                                           geolocation     id      mass  \
0    {'type': 'Point', 'coordinates': [6.08333, 50....      1      21.0 

In [62]:
display(nasa.head())

:@computed_region_cbhk_fwbd  :@computed_region_nnqa_25f4  fall  \
0                          NaN                          NaN  Fell   
1                          NaN                          NaN  Fell   
2                          NaN                          NaN  Fell   
3                          NaN                          NaN  Fell   
4                          NaN                          NaN  Fell   

                                         geolocation   id      mass      name  \
0  {'type': 'Point', 'coordinates': [6.08333, 50....    1      21.0    Aachen   
1  {'type': 'Point', 'coordinates': [10.23333, 56...    2     720.0    Aarhus   
2  {'type': 'Point', 'coordinates': [-113, 54.216...    6  107000.0      Abee   
3  {'type': 'Point', 'coordinates': [-99.9, 16.88...   10    1914.0  Acapulco   
4  {'type': 'Point', 'coordinates': [-64.95, -33....  370     780.0   Achiras   

  nametype     recclass    reclat    reclong                     year  
0    Valid           L5  50.77500    6.08333  1880-01-01T00:00:00.000  
1    Valid           H6  56.18333   10.23333  1951-01-01T00:00:00.000  
2    Valid          EH4  54.21667 -113.00000  1952-01-01T00:00:00.000  
3    Valid  Acapulcoite  16.88333  -99.90000  1976-01-01T00:00:00.000  
4    Valid           L6 -33.16667  -64.95000  1902-01-01T00:00:00.000

In [63]:
nasa.head()   # la ultima fila de cada celda del jupyter hace display

:@computed_region_cbhk_fwbd  :@computed_region_nnqa_25f4  fall  \
0                          NaN                          NaN  Fell   
1                          NaN                          NaN  Fell   
2                          NaN                          NaN  Fell   
3                          NaN                          NaN  Fell   
4                          NaN                          NaN  Fell   

                                         geolocation   id      mass      name  \
0  {'type': 'Point', 'coordinates': [6.08333, 50....    1      21.0    Aachen   
1  {'type': 'Point', 'coordinates': [10.23333, 56...    2     720.0    Aarhus   
2  {'type': 'Point', 'coordinates': [-113, 54.216...    6  107000.0      Abee   
3  {'type': 'Point', 'coordinates': [-99.9, 16.88...   10    1914.0  Acapulco   
4  {'type': 'Point', 'coordinates': [-64.95, -33....  370     780.0   Achiras   

  nametype     recclass    reclat    reclong                     year  
0    Valid           L5  50.77500    6.08333  1880-01-01T00:00:00.000  
1    Valid           H6  56.18333   10.23333  1951-01-01T00:00:00.000  
2    Valid          EH4  54.21667 -113.00000  1952-01-01T00:00:00.000  
3    Valid  Acapulcoite  16.88333  -99.90000  1976-01-01T00:00:00.000  
4    Valid           L6 -33.16667  -64.95000  1902-01-01T00:00:00.000

In [67]:
nasa['fall'].value_counts()

Fell     996
Found      4
Name: fall, dtype: int64

In [68]:
nasa.to_json('nasa.json', orient='records')

In [69]:
nasa.to_json('nasa.json', orient='index')

In [70]:
nasa.to_json('nasa.json', orient='columns')

In [81]:
cols = ['time', 'rad_flow', 'fpv_close', 'fpv_open', 'high', 'bypass', 'bpv_close', 'bpv_open', 'class', '']
tst_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/shuttle/shuttle.tst'

In [82]:
shuttle = pd.read_csv(tst_url, sep=' ', header=None)

shuttle.head()

0  1   2  3   4   5   6   7   8  9
0  55  0  81  0  -6  11  25  88  64  4
1  56  0  96  0  52  -4  40  44   4  4
2  50 -1  89 -7  50   0  39  40   2  1
3  53  9  79  0  42  -2  25  37  12  4
4  55  2  82  0  54  -6  26  28   2  1

In [83]:
shuttle.columns = cols

In [84]:
shuttle.head()

time  rad_flow  fpv_close  fpv_open  high  bypass  bpv_close  bpv_open  \
0    55         0         81         0    -6      11         25        88   
1    56         0         96         0    52      -4         40        44   
2    50        -1         89        -7    50       0         39        40   
3    53         9         79         0    42      -2         25        37   
4    55         2         82         0    54      -6         26        28   

   class     
0     64  4  
1      4  4  
2      2  1  
3     12  4  
4      2  1

In [85]:
shuttle.to_csv('datasets/shuttle.csv')

In [87]:
astronaut = pd.read_excel('datasets/astronauts.xls')

In [88]:
astronaut.head()

Name    Year  Group   Status Birth Date    Birth Place Gender  \
0   Joseph M. Acaba  2004.0   19.0   Active 1967-05-17  Inglewood, CA   Male   
1    Loren W. Acton     NaN    NaN  Retired 1936-03-07   Lewiston, MT   Male   
2  James C. Adamson  1984.0   10.0  Retired 1946-03-03     Warsaw, NY   Male   
3   Thomas D. Akers  1987.0   12.0  Retired 1951-05-20  St. Louis, MO   Male   
4       Buzz Aldrin  1963.0    3.0  Retired 1930-01-20  Montclair, NJ   Male   

                                          Alma Mater     Undergraduate Major  \
0  University of California-Santa Barbara; Univer...                 Geology   
1   Montana State University; University of Colorado     Engineering Physics   
2          US Military Academy; Princeton University             Engineering   
3                       University of Missouri-Rolla     Applied Mathematics   
4                           US Military Academy; MIT  Mechanical Engineering   

          Graduate Major Military Rank         Military Branch  Space Flights  \
0                Geology           NaN                     NaN              2   
1          Solar Physics           NaN                     NaN              1   
2  Aerospace Engineering       Colonel       US Army (Retired)              2   
3    Applied Mathematics       Colonel  US Air Force (Retired)              4   
4           Astronautics       Colonel  US Air Force (Retired)              2   

   Space Flight (hr)  Space Walks  Space Walks (hr)  \
0               3307            2              13.0   
1                190            0               0.0   
2                334            0               0.0   
3                814            4              29.0   
4                289            2               8.0   

                                            Missions Death Date Death Mission  
0             STS-119 (Discovery), ISS-31/32 (Soyuz)        NaT           NaN  
1                              STS 51-F (Challenger)        NaT           NaN  
2               STS-28 (Columbia), STS-43 (Atlantis)        NaT           NaN  
3  STS-41 (Discovery), STS-49 (Endeavor), STS-61 ...        NaT           NaN  
4                               Gemini 12, Apollo 11        NaT           NaN

In [91]:
astronaut['Undergraduate Major'].value_counts()

Physics                                  35
Aerospace Engineering                    33
Mechanical Engineering                   30
Aeronautical Engineering                 28
Electrical Engineering                   23
                                         ..
Astronomy                                 1
Marine Engineering & Nautical Science     1
Philosophy                                1
Bioscience                                1
Military Science                          1
Name: Undergraduate Major, Length: 83, dtype: int64

In [92]:
astronaut.to_csv('datasets/astronaut.csv')

In [93]:
astronaut.to_csv('datasets/astronaut.csv', sep='\t')

In [94]:
astronaut.to_csv('datasets/astronaut.csv', sep=';')

In [95]:
cols_fert=['Season', 'Age', 'Childish', 'Accident', 'Surgical', 'High fevers', 'Frequency of alcohol consumption', 'Smoking habit', 'Number of hours spent sitting per day', 'Output']

cols_fert

['Season',
 'Age',
 'Childish',
 'Accident',
 'Surgical',
 'High fevers',
 'Frequency of alcohol consumption',
 'Smoking habit',
 'Number of hours spent sitting per day',
 'Output']

In [97]:
fert = pd.read_csv('datasets/fertility_Diagnosis.txt', header=None)

fert.head()

0     1  2  3  4  5    6  7     8  9
0 -0.33  0.69  0  1  1  0  0.8  0  0.88  N
1 -0.33  0.94  1  0  1  0  0.8  1  0.31  O
2 -0.33  0.50  1  0  0  0  1.0 -1  0.50  N
3 -0.33  0.75  0  1  1  0  1.0 -1  0.38  N
4 -0.33  0.67  1  1  0  0  0.8 -1  0.50  O

In [98]:
fert.columns = cols_fert

In [99]:
fert.head()

Season   Age  Childish  Accident  Surgical  High fevers  \
0   -0.33  0.69         0         1         1            0   
1   -0.33  0.94         1         0         1            0   
2   -0.33  0.50         1         0         0            0   
3   -0.33  0.75         0         1         1            0   
4   -0.33  0.67         1         1         0            0   

   Frequency of alcohol consumption  Smoking habit  \
0                               0.8              0   
1                               0.8              1   
2                               1.0             -1   
3                               1.0             -1   
4                               0.8             -1   

   Number of hours spent sitting per day Output  
0                                   0.88      N  
1                                   0.31      O  
2                                   0.50      N  
3                                   0.38      N  
4                                   0.50      O

In [100]:
fert.to_csv('datasets/fert.csv')

In [104]:
fert.Age.mean()

0.669